export const provinceMap = {
  "4/0": "xinjiang",
  "4/1": "xinjiang",
  "4/2": "xinjiang",
  "6/3": "xinjiang",
  "15/4": "shanxi1",
  "17/6": "chongqing",
  "17/7": "chongqing",
  "5/1": "xinjiang",
  "5/2": "xinjiang",
  "5/3": "xinjiang",
  "5/4": "xinjiang",
  "5/5": "xinjiang",
  "5/6": "xinjiang",
  "6/7": "xinjiang",
  "7/7": "xinjiang",
  "7/6": "xinjiang",
  "7/5": "xinjiang",
  "7/4": "xinjiang",
  "7/3": "xinjiang",
  "7/2": "xinjiang",
  "8/7": "xinjiang",
  "8/6": "xinjiang",
  "8/5": "xinjiang",
  "8/4": "xinjiang",
  "8/3": "xinjiang",
  "8/2": "xinjiang",
  "9/10": "xizang",
  "9/9": "xizang",
  "9/8": "xizang",
  "9/7": "xinjiang",
  "9/6": "xinjiang",
  "9/5": "xinjiang",
  "9/4": "xinjiang",
  "17/5": "hubei",
  "18/5": "hubei",
  "19/5": "hubei",
  "18/6": "hubei",
  "24/12": "hainan",
  "10/10": "xizang",
  "10/9": "xizang",
  "10/8": "xizang",
  "10/7": "xizang",
  "10/6": "xinjiang",
  "10/5": "qinghai",
  "10/4": "gansu",
  "10/3": "gansu",
  "13/3": "ningxia",
  "14/4": "ningxia",
  "14/5": "gansu",
  "15/5": "gansu",
  "10/2": "neimenggu",
  "11/2": "neimenggu",
  "11/4": "gansu",
  "11/5": "qinghai",
  "12/5": "qinghai",
  "13/5": "qinghai",
  "11/6": "qinghai",
  "11/7": "qinghai",
  "12/7": "qinghai",
  "13/7": "qinghai",
  "13/6": "qinghai",
  "11/8": "xizang",
  "11/9": "xizang",
  "11/10": "xizang",
  "11/-4": "neimenggu",
  "11/-3": "neimenggu",
  "11/-2": "neimenggu",
  "12/0": "neimenggu",
  "12/10": "xizang",
  "12/9": "xizang",
  "13/8": "xizang",
  "13/9": "xizang",
  "13/10": "xizang",
  "13/11": "xizang",
  "14/9": "xizang",
  "14/10": "xizang",
  "15/10": "xizang",
  "15/9": "xizang",
  "12/6": "qinghai",
  "12/3": "gansu",
  "12/4": "gansu",
  "13/4": "gansu",
  "14/6": "qinghai",
  "12/2": "neimemggu",
  "12/1": "neimemggu",
  "12/-1": "neimemggu",
  "12/-2": "neimemggu",
  "12/-3": "neimemggu",
  "13/-3": "neimemggu",
  "13/-2": "neimemggu",
  "12/-4": "jilin",
  "9/-7": "neimenggu",
  "9/-6": "neimenggu",
  "10/-5": "neimenggu",
  "10/-6": "neimenggu",
  "10/-7": "heilongjiang",
  "11/-7": "heilongjiang",
  "11/-6": "heilongjiang",
  "11/-5": "heilongjiang",
  "12/-6": "heilongjiang",
  "12/-5": "heilongjiang",
  "13/-4": "jilin",
  "14/-4": "jilin",
  "14/-3": "liaoning",
  "14/-2": "liaoning",
  "15/-1": "liaoning",
  "13/-5": "heilongjiang",
  "22/8": "guangdong",
  "23/8": "guangdong",
  "22/9": "guangdong",
  "23/11": "guangdong",
  "22/6": "fujian",
  "22/7": "fujian",
  "24/7": "taiwan",
  "21/9": "guangxi",
  "20/10": "guangxi",
  "21/10": "guangxi",
  "22/10": "guangxi",
  "19/10": "yunnan",
  "18/10": "yunnan",
  "18/11": "yunnan",
  "19/11": "yunnan",
  "20/11": "yunnan",
  "20/12": "yunnan",
  "15/6": "sichuan",
  "16/6": "sichuan",
  "14/7": "sichuan",
  "15/7": "sichuan",
  "16/7": "sichuan",
  "16/8": "sichuan",
  "17/8": "sichuan",
  "17/9": "sichuan",
  "19/8": "guizhou",
  "19/9": "guizhou",
  "20/9": "guizhou",
  "19/7": "hunan",
  "20/7": "hunan",
  "20/8": "hunan",
  "21/8": "hunan",
  "19/2": "shanghai",
  "19/3": "shanghai",
  "18/3": "anhui",
  "19/4": "anhui",
  "18/2": "jiangsu",
  "20/4": "zhejiang",
  "21/4": "zhejiang",
  "21/5": "zhejiang",
  "20/5": "jiangxi",
  "20/6": "jiangxi",
  "21/6": "jiangxi",
  "21/7": "jiangxi",
  "16/1": "shandong",
  "16/0": "shandong",
  "17/2": "shandong",
  "16/3": "henan",
  "17/3": "henan",
  "17/4": "henan",
  "18/4": "henan",
  "14/-1": "hebei",
  "15/1": "hebei",
  "14/3": "shanxi1",
  "16/4": "henan",
  "12/8": "qinghai",
  "16/5": "shanxi1",
  "14/1": "shanxi2",
  "15/2": "shanxi2",
  "15/3": "shanxi2",
  "13/-1": "beijing",
  "15/0": "tianjin",
  "23/19": "Macao",
};
export const policy = {
  beijing: {
    name: "北京",
    high: 0,
    mid: 1,
    low: 1,
    foreignEntry: "7天集中隔离+3天居家健康监测",
    underRisk: "限制入京",
    normal: "48小时内核酸阴性证明+北京健康宝绿码；落地居家健康监测3天+3天2检",
  },
  tianjing: {
    name: "天津",
    high: 15,
    mid: 15,
    low: 0,
    foreignEntry: "7天集中隔离+3天居家健康监测",
    underRisk: "高风险区：7天集中隔离+7天5检；中风险区：7天居家隔离+7天3检",
    normal: "48小时内核酸阴性证明+天津健康码绿码；落地核酸",
  },
  shanghai: {
    name: "上海",
    high: 0,
    mid: 17,
    low: 14,
    foreignEntry: "7天集中隔离+3天居家健康监测",
    underRisk:
      "提前申报；48小时内核酸阴性证明；高风险区：7天集中隔离；中风险区：7天居家隔离",
    normal: "提前申报；48小时内核酸阴性证明；3天3检",
  },
  chongqing: {
    name: "重庆",
    high: 16,
    mid: 22,
    low: 7,
    foreignEntry: "7天集中隔离+3天居家健康监测",
    underRisk: "高风险区：7天集中隔离+7天5检；中风险区：7天居家隔离+7天3检",
    normal: "提前申报；48小时内核酸阴性证明；3天3检",
  },
  henan: {
    name: "河南省",
    high: 11,
    mid: 36,
    low: 6,
    foreignEntry: "7天集中隔离+3天居家健康监测",
    underRisk: "高风险区：7天集中隔离；中风险区：7天居家隔离",
    normal: "落地报备；24小时内核酸阴性证明；落地核酸+3天3检 ",
  },
  hubei: {
    name: "湖北省",
    high: 0,
    mid: 0,
    low: 0,
    foreignEntry: "7天集中隔离+3天居家健康监测",
    underRisk:
      "健康申报；高风险区：7天集中隔离+7天5检；中风险区：7天居家隔离+7天3检",
    normal: "健康申报；5天4检 ",
  },
  hunan: {
    name: "湖南省",
    high: 0,
    mid: 0,
    low: 0,
    foreignEntry: "7天集中隔离+3天居家健康监测",
    underRisk: "高风险区：7天集中隔离+7天5检；中风险区：7天居家隔离+7天3检",
    normal: "落地报备；48小时内核酸阴性证明 ",
  },
  guangdong: {
    name: "广东省",
    high: 54,
    mid: 69,
    low: 24,
    foreignEntry: "7天集中隔离+3天居家健康监测",
    underRisk: "高风险区：7天集中隔离+7天5检；中风险区：7天居家隔离+7天3检",
    normal: "48小时内核酸阴性证明；3天3检 ",
  },
  hainan: {
    name: "海南省",
    high: 0,
    mid: 0,
    low: 0,
    foreignEntry: "7天集中隔离+3天居家健康监测",
    underRisk: "高风险区：7天集中隔离+7天5检",
    normal: "落地报备；3天3检 ",
  },
  shandong: {
    name: "山东省",
    high: 2,
    mid: 2,
    low: 1,
    foreignEntry: "7天集中隔离+3天居家健康监测",
    underRisk: "高风险区：7天集中隔离；中风险区：7天居家隔离",
    normal: "3天2检",
  },
  sichuan: {
    name: "四川省",
    high: 2,
    mid: 1,
    low: 3,
    foreignEntry: "7天集中隔离+3天居家健康监测",
    underRisk: "高风险区：7天集中隔离+7天5检；中风险区：7天居家隔离+7天3检",
    normal: "3天3检 ",
  },
  guizhou: {
    name: "贵州省",
    high: 0,
    mid: 0,
    low: 0,
    foreignEntry: "7天集中隔离+3天居家健康监测",
    underRisk:
      "贵州健康码申报；高风险区：7天集中隔离+7天5检；中风险区：7天居家隔离+7天3检",
    normal: "贵州健康码申报；48小时内核酸阴性证明；3天3检 ",
  },
  yunnan: {
    name: "云南省",
    high: 0,
    mid: 0,
    low: 0,
    foreignEntry: "7天集中隔离+3天居家健康监测",
    underRisk:
      "落地报备；中高风险区按照《新型冠状病毒肺炎防控方案（第九版）》管控",
    normal: "落地报备；3天2检",
  },
  shanxi2: {
    name: "山西省",
    high: 7,
    mid: 3,
    low: 2,
    underRisk: "高风险区：7天集中隔离+7天5检；中风险区：7天居家隔离+7天3检",
    normal: "落地核酸+3天2检",
    foreignEntry: "7天集中隔离+3天居家健康监测",
  },

  liaoning: {
    name: "辽宁省",
    high: 0,
    mid: 0,
    low: 0,
    underRisk: "高风险区：7天集中隔离+7天5检；中风险区：7天居家隔离+7天3检",
    normal: "3天2检",
    foreignEntry: "7天集中隔离+3天居家健康监测",
  },

  jilin: {
    name: "吉林省",
    high: 2,
    mid: 0,
    low: 0,
    underRisk: "高风险区：7天集中隔离+7天5检；中风险区：7天居家隔离+7天3检",
    normal: "3天2检",
    foreignEntry: "7天集中隔离+3天居家健康监测",
  },

  heilongjiang: {
    name: "黑龙江省",
    high: 0,
    mid: 0,
    low: 0,
    underRisk: "中高风险区：7天居家隔离+7天7检",
    normal: "3+4管控措施；7天7检",
    foreignEntry: "7天集中隔离+3天居家健康监测",
  },

  jiangsu: {
    name: "江苏省",
    high: 2,
    mid: 15,
    low: 7,
    underRisk:
      "高风险区：7天集中隔离+7天5检；中风险区：7天居家隔离+7天3检；低风险区：7天5检",
    normal: "落地核酸+3天3检3+4管控措施；7天7检",
    foreignEntry: "7天集中隔离+3天居家健康监测",
  },

  zhejiang: {
    name: "浙江省",
    high: 0,
    mid: 0,
    low: 0,
    underRisk: "高风险区：7天集中隔离；中风险区：7天居家隔离；低风险区：3天2检",
    normal: " ",
    foreignEntry: "7天集中隔离+3天居家健康监测",
  },

  anhui: {
    name: "安徽省",
    high: 1,
    mid: 35,
    low: 5,
    underRisk: "中高风险区：集中隔离+48小时核酸查验",
    normal: " ",
    foreignEntry: "7天集中隔离+3天居家健康监测",
  },
  fujian: {
    name: "福建省",
    high: 0,
    mid: 35,
    low: 6,
    underRisk: "高风险区：7天集中隔离+7天5检；中风险区：7天居家隔离+7天3检",
    normal: "48小时内核酸阴性证明；3天2检",
    foreignEntry: "7天集中隔离+3天居家健康监测",
  },

  jiangxi: {
    name: "江西省",
    high: 0,
    mid: 0,
    low: 0,
    underRisk:
      "48小时内核酸证明；高风险区：7天集中隔离+7天5检；中风险区：7天居家隔离+7天3检；低风险区：落地核酸+3天2检",
    normal: " ",
    foreignEntry: "7天集中隔离+3天居家健康监测",
  },
  shanxi1: {
    name: "陕西省",
    high: 51,
    mid: 87,
    low: 10,
    foreignEntry: "7天集中隔离+3天居家健康监测",
    underRisk: "高风险区：7天集中隔离；中风险区：7天居家隔离",
    normal: "低风险区：3天2检；其他详见西安市疫情防控政策",
  },
  gansu: {
    name: "甘肃省",
    high: 5,
    mid: 16,
    low: 2,
    foreignEntry: "7天集中隔离+3天居家健康监测",
    underRisk: "高风险区：7天集中隔离；中风险区：7天居家隔离",
    normal: "低风险区：3天2检",
  },
  qinghai: {
    name: "青海省",
    high: 154,
    mid: 102,
    low: 4,
    foreignEntry: "7天集中隔离+3天居家健康监测",
    underRisk: "高风险区：7天集中隔离；中风险区：7天居家隔离",
    normal: "低风险区：3天2检",
  },
  neimenggu: {
    name: "内蒙古自治区",
    high: 268,
    mid: 203,
    low: 5,
    foreignEntry: "严格限制",
    underRisk: "严格限制",
    normal: "严格限制",
  },
  guangxi: {
    name: "广西壮族自治区",
    high: 0,
    mid: 0,
    low: 0,
    foreignEntry: "7天集中隔离+3天居家健康监测",
    underRisk: "落地报备；风险区人员提前与目的地社区联系了解相关政策",
    normal: "落地报备；48小时内核酸阴性证明；落地核酸+3天2检",
  },
  xizang: {
    name: "西藏自治区",
    high: 0,
    mid: 0,
    low: 0,
    foreignEntry: "7天集中隔离+3天居家健康监测",
    underRisk:
      "提前3天报备；高风险区：7天集中隔离+7天5检；中风险区：7天居家隔离+7天3检",
    normal: "提前3天报备；48小时内核酸阴性证明；3天2检",
  },
  ningxia: {
    name: "宁夏回族自治区",
    high: 7,
    mid: 14,
    low: 5,
    foreignEntry: "7天集中隔离+3天居家健康监测",
    underRisk: "高风险区：7天集中隔离+7天5检；中风险区：7天居家隔离+7天3检",
    normal: "48小时内核酸阴性证明；3天2检",
  },
  xinjiang: {
    name: "新疆维吾尔自治区",
    high: 841,
    mid: 125,
    low: 6,
    foreignEntry: "7天集中隔离+3天居家健康监测",
    underRisk: "入疆申报；高风险区：7天集中隔离；中风险区：7天居家隔离",
    normal: "入疆申报；3天2检",
  },
};
